language: node_js

services:
  - couchdb

sudo: false
node_js:
  - "stable"
addons:
  - firefox: "41.0.1"
script: npm run $COMMAND

env:
  matrix:
  - COMMAND=test
  - CLIENT=selenium:firefox:41.0.1 COMMAND=test
  - CLIENT=selenium:phantomjs COMMAND=test
  - COMMAND=coverage

branches:
  only:
  - master
